### PR TITLE
First MapLibre experiment

### PR DESCRIPTION
**Pull request by tuokait**
- Show map on UI
- Creater markers on map when clicked
- Markers can be moved by dragging them
- Markers can be deleted by clicking them (to open PopupInfo) and then clicking delete button

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-maplibre-experiment/1)

### CODE REVIEW

**Review by haphut — CHANGES_REQUESTED** [review]
Great stuff! Thank you for the perseverance.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-maplibre-experiment/1#-:-Mbb3_9I3OBuLs0bUhqT:bpbjlmb)* status: 2 of 10 files reviewed, 4 unresolved discussions (waiting on @haphut and @tk-vincit)

___
*[package.json, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-maplibre-experiment/1#-Mbb3XuP7kxsScpFbght:-Mbb3XuP7kxsScpFbghu:bqo033y) ([raw file](https://github.com/hsldevcom/jore4-maplibre-experiment/blob/c773bd4ddac2f15ed9cc08693b98e2054a0fc8c6/package.json#L2)):*
> ```JSON
> {
>   "name": "jore4-openlayers-experiement",
> ```

`jore4-maplibre-experiment`
___
*[package.json, line 23 at r2](https://reviewable.io/reviews/hsldevcom/jore4-maplibre-experiment/1#-Mbb3xmcDeEmqjJMZ7_r:-Mbb3xmcDeEmqjJMZ7_s:b-ido0or) ([raw file](https://github.com/hsldevcom/jore4-maplibre-experiment/blob/c421832b6350b051aae79d5c2354e8298a00db2b/package.json#L23)):*
> ```JSON
>     "react-dom": "17.0.2",
>     "react-i18next": "^11.8.12",
>     "react-map-gl": "^6.1.15",
> ```

Also `maplibre` and maybe `@types/maplibre-gl`.
___
*[README.md, line 3 at r1](https://reviewable.io/reviews/hsldevcom/jore4-maplibre-experiment/1#-Mbb3jRtCKVCemLOUC4_:-Mbb3jRtCKVCemLOUC4a:bf20bcw) ([raw file](https://github.com/hsldevcom/jore4-maplibre-experiment/blob/c773bd4ddac2f15ed9cc08693b98e2054a0fc8c6/README.md#L3)):*
> ```Markdown
> # jore4-maplibre-experiment
> 
> This repository is based on [HSLdevcom/jore4-ui](https://github.com/HSLdevcom/jore4-ui). The purpose of this repository is to have playground where OpenLayers map libraries can be experimented.
> ```

Maplibre again, not OpenLayers.
___
*[yarn.lock, line 851 at r2](https://reviewable.io/reviews/hsldevcom/jore4-maplibre-experiment/1#-Mbb4BJVCVcPsySTtihb:-Mbb4BJVCVcPsySTtihc:btvszhu) ([raw file](https://github.com/hsldevcom/jore4-maplibre-experiment/blob/c421832b6350b051aae79d5c2354e8298a00db2b/yarn.lock#L851)):*
> ```YAML
>   integrity sha1-7ihweulOEdK4J7y+UnC86n8+ce4=
> 
> "@types/mapbox-gl@^2.0.3":
> ```

`react-map-gl` brings in proprietary libraries like `mapbox-gl`. I think they should be cleaned out.

**Review by haphut — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-maplibre-experiment/1)* status: 2 of 10 files reviewed, 4 unresolved discussions (waiting on @haphut and @tk-vincit)

___
*[yarn.lock, line 851 at r2](https://reviewable.io/reviews/hsldevcom/jore4-maplibre-experiment/1#-Mbb4BJVCVcPsySTtihb:-Mbb4iW95gQu0AweY-Gm:b-45vdzz) ([raw file](https://github.com/hsldevcom/jore4-maplibre-experiment/blob/c421832b6350b051aae79d5c2354e8298a00db2b/yarn.lock#L851)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

`react-map-gl` brings in proprietary libraries like `mapbox-gl`. I think they should be cleaned out.
</blockquote></details>

It is not super easy to figure out which are proprietary because not everything by mapbox is. I tested that this worked (with `npm`):

1. Install maplibre with npm aliases:`npm install mapbox-gl@npm:maplibre-gl @types/mapbox-gl@npm:@types/maplibre-gl`
1. `npm install react-map-gl`

I checked every mapbox library installed by `react-map-gl` in the second step and none of those were proprietary.

Probably running `npm install @types/react-map-gl` after that would install no proprietary libraries.

**Review by haphut — COMMENTED** [review]
> Reviewed 4 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-maplibre-experiment/1)* status: 4 of 10 files reviewed, 3 unresolved discussions (waiting on @haphut and @tk-vincit)

___
*[package.json, line 23 at r2](https://reviewable.io/reviews/hsldevcom/jore4-maplibre-experiment/1#-Mbb3xmcDeEmqjJMZ7_r:-MbbIu9X21iaANeX0GLh:bnc3ikl) ([raw file](https://github.com/hsldevcom/jore4-maplibre-experiment/blob/c421832b6350b051aae79d5c2354e8298a00db2b/package.json#L23)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

Also `maplibre` and maybe `@types/maplibre-gl`.
</blockquote></details>

Actually after testing I prefer the approach I suggested on the lock file of installing maplibre as an npm alias.

**Review by lassemaatta — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-maplibre-experiment/1)* status: 4 of 10 files reviewed, 3 unresolved discussions (waiting on @haphut and @tk-vincit)

___
*[yarn.lock, line 851 at r2](https://reviewable.io/reviews/hsldevcom/jore4-maplibre-experiment/1#-Mbb4BJVCVcPsySTtihb:-MbbJuUmDOUGGw48NrBR:b-sceqa7) ([raw file](https://github.com/hsldevcom/jore4-maplibre-experiment/blob/c421832b6350b051aae79d5c2354e8298a00db2b/yarn.lock#L851)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

It is not super easy to figure out which are proprietary because not everything by mapbox is. I tested that this worked (with `npm`):

1. Install maplibre with npm aliases:`npm install mapbox-gl@npm:maplibre-gl @types/mapbox-gl@npm:@types/maplibre-gl`
1. `npm install react-map-gl`

I checked every mapbox library installed by `react-map-gl` in the second step and none of those were proprietary.

Probably running `npm install @types/react-map-gl` after that would install no proprietary libraries.
</blockquote></details>

Would something like https://www.npmjs.com/package/license-compliance help us here to identify non-compliant licenses/libraries?

**Review by haphut — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-maplibre-experiment/1)* status: 4 of 10 files reviewed, 3 unresolved discussions (waiting on @haphut and @tk-vincit)

___
*[src/components/map/Map.tsx, line 24 at r3](https://reviewable.io/reviews/hsldevcom/jore4-maplibre-experiment/1#-MbbJcDx4gQqOAyyhsuE:-MbbJcDx4gQqOAyyhsuF:ba26oze) ([raw file](https://github.com/hsldevcom/jore4-maplibre-experiment/blob/5c7a4482f9d159767215909eabe3dc9fd0a2b5f1/src/components/map/Map.tsx#L24)):*
> ```XML
>   ]);
>   const onClick = (e: MapEvent) => {
>     setMarkers([...markers, mapLngLatToPoint(e.lngLat)]);
> ```

When we had issues with clicks going through elements in another project, our hack was to just `e.preventDefault()` here.

**Review by haphut — COMMENTED** [review]
> Reviewed 6 of 6 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-maplibre-experiment/1)* status: 8 of 10 files reviewed, 3 unresolved discussions (waiting on @haphut, @lassemaatta, and @tk-vincit)

___
*[yarn.lock, line 851 at r2](https://reviewable.io/reviews/hsldevcom/jore4-maplibre-experiment/1#-Mbb4BJVCVcPsySTtihb:-MbbO-rv9uzoSwa41eLp:bshwy1h) ([raw file](https://github.com/hsldevcom/jore4-maplibre-experiment/blob/c421832b6350b051aae79d5c2354e8298a00db2b/yarn.lock#L851)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

Would something like https://www.npmjs.com/package/license-compliance help us here to identify non-compliant licenses/libraries?
</blockquote></details>

@lassemaatta Nice, that looks cool and simple. I've tried Fossa and Snyk which check for license incompatibilities without having to specify a list of allowed licenses but I was not impressed with the results at the time.

**Comment by tuokait** [comment]
Development efforts have been moved to https://github.com/HSLdevcom/jore4-ui and thus it's not worth it to continue working with this pr. Probably it would have made sense to merge this to `main` branch, but as review is still pending I'm closing this PR and leaving this branch undeleted.

Discussion about licences noted in https://github.com/HSLdevcom/jore4/issues/531

**Pull request closed without merging**
